id: P005534
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:57:57.660343
source_metadata:
  id: bdr:W8LS17242
  title: རྣམ་སྲས་ལ་མཆོད་གཏོར་འབུལ་བའི་རིམ་པ་དངོས་གྲུབ་ཀྱི་བང་མཛོད།
  author: ''
  volumes:
    aa4cf33cecd649b0bf291e73348e37b3:
      image_group_id: I8LS17274
      title: ''
      volume_number: 1
      total_pages: 26
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
