id: P005534
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS17242
  title: རྣམ་སྲས་ལ་མཆོད་གཏོར་འབུལ་བའི་རིམ་པ་དངོས་གྲུབ་ཀྱི་བང་མཛོད།
  author: ''
  volumes:
    aa4cf33cecd649b0bf291e73348e37b3:
      image_group_id: I8LS17274
      title: ''
      volume_number: 1
      total_pages: 26
      base_file: v001.txt
