id: IB17A4878
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T17:06:43+00:00'
last_modified: '2022-06-08T04:43:39.891264+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17242
  title: རྣམ་སྲས་ལ་མཆོད་གཏོར་འབུལ་བའི་རིམ་པ་དངོས་གྲུབ་ཀྱི་བང་མཛོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '5805':
      image_group_id: I8LS17274
      title: ''
      total_pages: 26
      order: 1
      base_file: 5805.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
